# Generated by Django 2.2.5 on 2020-12-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='listing_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
