# Generated by Django 2.2.5 on 2020-12-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Cars', 'Cars'), ('Mobiles', 'Mobiles'), ('Fashion', 'Fashion'), ('Property', 'Property'), ('Bikes', 'Bikes'), ('Jobs', 'Jobs'), ('Furniture', 'Furniture'), ('Books&Sports', 'Books&Sports'), ('Electronics', 'Electronics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('PB', 'Punjab'), ('MP', 'Madhya Pradesh'), ('AS', 'Assam'), ('MI', 'Sikkim'), ('WB', 'West Bengal'), ('OD', 'Odisha'), ('HP', 'Haryana'), ('NL', 'Nagaland'), ('KA', 'Karnataka'), ('MZ', 'Mizoram'), ('CG', 'Chhattisgarh'), ('UK', 'Uttarakhand'), ('JH', 'Jharkhand'), ('KL', 'Kerala'), ('ML', 'Meghalaya'), ('AP', 'Andhra Pradesh'), ('UP', 'Uttar Pradesh'), ('RJ', 'Rajasthan'), ('TN', 'Tamil Nadu'), ('BR', 'Bihar'), ('AR', 'Arunachal Pradesh'), ('TR', 'Tripura'), ('MH', 'Maharashtra'), ('TS', 'Telegana'), ('MN', 'Manipur'), ('GA', 'Goa'), ('GJ', 'Gujarat')], max_length=100),
        ),
    ]
